---- テストデータ ※挿入する場合はコメントアウトを外してアプリケーションを実行する
---- 著者
--INSERT INTO authors (name, birth_date) VALUES ('山田太郎', '1975-05-20');
--INSERT INTO authors (name, birth_date) VALUES ('佐藤一郎', '1980-11-12');
--INSERT INTO authors (name, birth_date) VALUES ('田中花子', '1965-07-30');
--INSERT INTO authors (name, birth_date) VALUES ('渡辺サトシ', '1990-04-15');
--INSERT INTO authors (name, birth_date) VALUES ('斎藤信子', '1983-09-05');
--
---- 書籍
--INSERT INTO books (title, price, publish_status) VALUES ('The Silent Woods', 1500, '1');
--INSERT INTO books (title, price, publish_status) VALUES ('Echoes of the Sea', 2000, '0');
--INSERT INTO books (title, price, publish_status) VALUES ('Mysteries Unveiled', 2500, '1');
--INSERT INTO books (title, price, publish_status) VALUES ('Journey to Nowhere', 1800, '0');
--
---- 書籍・著者
---- 'The Silent Woods'(共著)
--INSERT INTO book_authors (book_id, author_id) VALUES (1, 1); -- 山田太郎
--INSERT INTO book_authors (book_id, author_id) VALUES (1, 2); -- 佐藤一郎
--
---- 'Echoes of the Sea'
--INSERT INTO book_authors (book_id, author_id) VALUES (2, 3); -- 田中花子
--
---- 'Mysteries Unveiled'
--INSERT INTO book_authors (book_id, author_id) VALUES (3, 4); -- 渡辺サトシ
--
---- 'Journey to Nowhere'
--INSERT INTO book_authors (book_id, author_id) VALUES (4, 1); -- 山田太郎
